In [1]:
import pandas as pd

In [2]:
apple = pd.read_csv('apple.csv', index_col = 0)
chase = pd.read_csv('chase.csv', index_col = 0)
microsoft = pd.read_csv('microsoft.csv', index_col = 0)
tesla = pd.read_csv('tesla.csv', index_col = 0)

In [3]:
apple.head(50)

                     Open    High     Low   Close  Adj Close       Volume
Date
2025-02-03         229.99  231.83  225.70  228.01     226.98   73063300.0
2025-02-04         227.25  233.13  226.65  232.80     231.75   45067300.0
2025-02-05         228.53  232.67  228.27  232.47     231.42   39620300.0
2025-02-06         231.29  233.80  230.43  233.22     232.17   29925300.0
2025-02-07          232.6  234.00  227.26  227.63     226.61   39707200.0
2025-02-10  0.25 Dividend     NaN     NaN     NaN        NaN          NaN
2025-02-10         229.57  230.59  227.20  227.65     226.87   33115600.0
2025-02-11          228.2  235.23  228.13  232.62     231.83   53718400.0
2025-02-12          231.2  236.96  230.68  236.87     236.06   45243300.0
2025-02-13         236.91  242.34  235.57  241.53     240.71   53614100.0
2025-02-14         241.25  245.55  240.99  244.60     243.77   40896200.0
2025-02-18         244.15  245.18  241.84  244.47     243.64   48822500.0
2025-02-19         244.66  246.01  243.16  244.87     244.04   32204200.0
2025-02-20         244.94  246.78  244.29  245.83     244.99   32316900.0
2025-02-21         245.95  248.69  245.22  245.55     244.71   53197400.0
2025-02-24         244.93  248.86  244.42  247.10     246.26   51326400.0
2025-02-25            248  250.00  244.91  247.04     246.20   48013300.0
2025-02-26         244.33  244.98  239.13  240.36     239.54   44433600.0
2025-02-27         239.41  242.46  237.06  237.30     236.49   41153600.0
2025-02-28         236.95  242.09  230.20  241.84     241.02   56833400.0
2025-03-03         241.79  244.03  236.11  238.03     237.22   47184000.0
2025-03-04         237.71  240.07  234.68  235.93     235.13   53798100.0
2025-03-05         235.42  236.55  229.23  235.74     234.94   47227600.0
2025-03-06         234.44  237.86  233.16  235.33     234.53   45170400.0
2025-03-07         235.11  241.37  234.76  239.07     238.26   46273600.0
2025-03-10         235.54  236.16  224.22  227.48     226.70   72071200.0
2025-03-11         223.81  225.84  217.45  220.84     220.09   76137400.0
2025-03-12         220.14  221.75  214.91  216.98     216.24   62547500.0
2025-03-13         215.95  216.84  208.42  209.68     208.97   61368300.0
2025-03-14         211.25  213.95  209.58  213.49     212.76   60107600.0
2025-03-17         213.31  215.22  209.97  214.00     213.27   48073400.0
2025-03-18         214.16  215.15  211.49  212.69     211.97   42432400.0
2025-03-19         214.22  218.76  213.75  215.24     214.51   54385400.0
2025-03-20         213.99  217.49  212.22  214.10     213.37   48862900.0
2025-03-21         211.56  218.84  211.28  218.27     217.53   94127800.0
2025-03-24            221  221.48  218.58  220.73     219.98   44299500.0
2025-03-25         220.77  224.10  220.08  223.75     222.99   34493600.0
2025-03-26         223.51  225.02  220.47  221.53     220.78   34466100.0
2025-03-27         221.39  224.99  220.56  223.85     223.09   37094800.0
2025-03-28         221.67  223.81  217.68  217.90     217.16   39818600.0
2025-03-31         217.01  225.62  216.23  222.13     221.37   65299300.0
2025-04-01         219.81  223.68  218.90  223.19     222.43   36412700.0
2025-04-02         221.32  225.19  221.02  223.89     223.13   35905900.0
2025-04-03         205.54  207.49  201.25  203.19     202.50  103419000.0
2025-04-04         193.89  199.88  187.34  188.38     187.74  125910900.0
2025-04-07          177.2  194.15  174.62  181.46     180.84  160466300.0
2025-04-08          186.7  190.34  169.21  172.42     171.83  120859500.0
2025-04-09         171.95  200.61  171.89  198.85     198.17  184395900.0
2025-04-10         189.07  194.78  183.00  190.42     189.77  121880000.0
2025-04-11          186.1  199.54  186.06  198.15     197.47   87435900.0

In [4]:
apple.isna().any()

Open         False
High          True
Low           True
Close         True
Adj Close     True
Volume        True
dtype: bool

In [5]:
chase.isna().any()

Open         False
High          True
Low           True
Close         True
Adj Close     True
Volume        True
dtype: bool

In [6]:
microsoft.isna().any()

Open         False
High          True
Low           True
Close         True
Adj Close     True
Volume        True
dtype: bool

In [7]:
tesla.isna().any()

Open         False
High         False
Low          False
Close        False
Adj Close    False
Volume       False
dtype: bool

In [8]:
apple = apple.dropna()

In [10]:
chase = chase.dropna()

In [11]:
microsoft = microsoft.dropna()

In [12]:
tesla = tesla.dropna()

In [ ]:
apple.isna().any()

In [13]:
chase.isna().any()

Open         False
High         False
Low          False
Close        False
Adj Close    False
Volume       False
dtype: bool

In [14]:
microsoft.isna().any()

Open         False
High         False
Low          False
Close        False
Adj Close    False
Volume       False
dtype: bool

In [15]:
tesla.isna().any()

Open         False
High         False
Low          False
Close        False
Adj Close    False
Volume       False
dtype: bool

In [16]:
dfs = [apple, chase, microsoft, tesla]

In [17]:
apple.columns

Index(['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

for df in dfs:
    df.columns = df.columns.str.strip()

In [19]:
for df in dfs:
    df['MA5'] = df.Close.rolling(5).mean()
    df['MA20'] = df.Close.rolling(20).mean()
    df['MA50'] = df.Close.rolling(50).mean()

In [20]:
apple.head()

,Open,High,Low,Close,Adj Close,Volume,MA5,MA20,MA50
Date,,,,,,,,,
2025-02-03,229.99,231.83,225.70,228.01,226.98,73063300.0,NaN,NaN,NaN
2025-02-04,227.25,233.13,226.65,232.80,231.75,45067300.0,NaN,NaN,NaN
2025-02-05,228.53,232.67,228.27,232.47,231.42,39620300.0,NaN,NaN,NaN
2025-02-06,231.29,233.80,230.43,233.22,232.17,29925300.0,NaN,NaN,NaN
2025-02-07,232.6,234.00,227.26,227.63,226.61,39707200.0,230.826,NaN,NaN

In [21]:
for df in dfs:
    df['Previous day close price'] = df['Close'].shift(1)

In [22]:
for df in dfs:
    df['Change in price'] = df['Close']- df['Previous day close price']

In [23]:
for df in dfs:
    df['Percent change in price'] = df.Close.pct_change()

In [24]:
apple.head()

,Open,High,Low,Close,Adj Close,Volume,MA5,MA20,MA50,Previous day close price,Change in price,Percent change in price
Date,,,,,,,,,,,,
2025-02-03,229.99,231.83,225.70,228.01,226.98,73063300.0,NaN,NaN,NaN,NaN,NaN,NaN
2025-02-04,227.25,233.13,226.65,232.80,231.75,45067300.0,NaN,NaN,NaN,228.01,4.79,0.021008
2025-02-05,228.53,232.67,228.27,232.47,231.42,39620300.0,NaN,NaN,NaN,232.80,-0.33,-0.001418
2025-02-06,231.29,233.80,230.43,233.22,232.17,29925300.0,NaN,NaN,NaN,232.47,0.75,0.003226
2025-02-07,232.6,234.00,227.26,227.63,226.61,39707200.0,230.826,NaN,NaN,233.22,-5.59,-0.023969

In [25]:
for df in dfs:
    df['Previous day volume'] = df['Volume'].shift(1)

In [26]:
for df in dfs:
    df['Change in volume'] = df['Volume']- df['Previous day volume']

In [27]:
apple.head()

,Open,High,Low,Close,Adj Close,Volume,MA5,MA20,MA50,Previous day close price,Change in price,Percent change in price,Previous day volume,Change in volume
Date,,,,,,,,,,,,,,
2025-02-03,229.99,231.83,225.70,228.01,226.98,73063300.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-02-04,227.25,233.13,226.65,232.80,231.75,45067300.0,NaN,NaN,NaN,228.01,4.79,0.021008,73063300.0,-27996000.0
2025-02-05,228.53,232.67,228.27,232.47,231.42,39620300.0,NaN,NaN,NaN,232.80,-0.33,-0.001418,45067300.0,-5447000.0
2025-02-06,231.29,233.80,230.43,233.22,232.17,29925300.0,NaN,NaN,NaN,232.47,0.75,0.003226,39620300.0,-9695000.0
2025-02-07,232.6,234.00,227.26,227.63,226.61,39707200.0,230.826,NaN,NaN,233.22,-5.59,-0.023969,29925300.0,9781900.0

In [28]:
apple.dtypes

Open                         object
High                        float64
Low                         float64
Close                       float64
Adj Close                   float64
Volume                      float64
MA5                         float64
MA20                        float64
MA50                        float64
Previous day close price    float64
Change in price             float64
Percent change in price     float64
Previous day volume         float64
Change in volume            float64
dtype: object

In [29]:
apple.head()

,Open,High,Low,Close,Adj Close,Volume,MA5,MA20,MA50,Previous day close price,Change in price,Percent change in price,Previous day volume,Change in volume
Date,,,,,,,,,,,,,,
2025-02-03,229.99,231.83,225.70,228.01,226.98,73063300.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-02-04,227.25,233.13,226.65,232.80,231.75,45067300.0,NaN,NaN,NaN,228.01,4.79,0.021008,73063300.0,-27996000.0
2025-02-05,228.53,232.67,228.27,232.47,231.42,39620300.0,NaN,NaN,NaN,232.80,-0.33,-0.001418,45067300.0,-5447000.0
2025-02-06,231.29,233.80,230.43,233.22,232.17,29925300.0,NaN,NaN,NaN,232.47,0.75,0.003226,39620300.0,-9695000.0
2025-02-07,232.6,234.00,227.26,227.63,226.61,39707200.0,230.826,NaN,NaN,233.22,-5.59,-0.023969,29925300.0,9781900.0

In [30]:
apple.dtypes

Open                         object
High                        float64
Low                         float64
Close                       float64
Adj Close                   float64
Volume                      float64
MA5                         float64
MA20                        float64
MA50                        float64
Previous day close price    float64
Change in price             float64
Percent change in price     float64
Previous day volume         float64
Change in volume            float64
dtype: object

In [31]:
for df in dfs:
    df['Percent change in volume'] = df.Volume.pct_change()

In [32]:
for df in dfs:
    df['VMA5'] = df.Volume.rolling(5).mean()
    df['VMA20'] = df.Volume.rolling(20).mean()

In [33]:
for df in dfs:
    df['Volume_Osc'] = (df['VMA5']- df['VMA20'])/df['VMA20'] * 100

In [34]:
for df in dfs:
    df['Open'] = pd.to_numeric(df['Open'], errors='coerce')

In [35]:
apple.dtypes

Open                        float64
High                        float64
Low                         float64
Close                       float64
Adj Close                   float64
Volume                      float64
MA5                         float64
MA20                        float64
MA50                        float64
Previous day close price    float64
Change in price             float64
Percent change in price     float64
Previous day volume         float64
Change in volume            float64
Percent change in volume    float64
VMA5                        float64
VMA20                       float64
Volume_Osc                  float64
dtype: object

In [36]:
for df in dfs:
    df['Previous day open price'] = df['Open'].shift(1)
for df in dfs:
    df['Change in open price'] = df['Open']- df['Previous day open price']
for df in dfs:
    df['Percent change in open price'] = df.Open.pct_change()

In [37]:
for df in dfs:
    df['Previous day high price'] = df['High'].shift(1)
for df in dfs:
    df['Change in high price'] = df['High']- df['Previous day high price']
for df in dfs:
    df['Percent change in high price'] = df.High.pct_change()

In [38]:
for df in dfs:
    df['Previous day low price'] = df['Low'].shift(1)
for df in dfs:
    df['Change in low price'] = df['Low']- df['Previous day low price']
for df in dfs:
    df['Percent change in low price'] = df.Low.pct_change()

In [39]:
apple.head()

,Open,High,Low,Close,Adj Close,Volume,MA5,MA20,MA50,Previous day close price,...,Volume_Osc,Previous day open price,Change in open price,Percent change in open price,Previous day high price,Change in high price,Percent change in high price,Previous day low price,Change in low price,Percent change in low price
Date,,,,,,,,,,,,,,,,,,,,,
2025-02-03,229.99,231.83,225.70,228.01,226.98,73063300.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-02-04,227.25,233.13,226.65,232.80,231.75,45067300.0,NaN,NaN,NaN,228.01,...,NaN,229.99,-2.74,-0.011914,231.83,1.30,0.005608,225.70,0.95,0.004209
2025-02-05,228.53,232.67,228.27,232.47,231.42,39620300.0,NaN,NaN,NaN,232.80,...,NaN,227.25,1.28,0.005633,233.13,-0.46,-0.001973,226.65,1.62,0.007148
2025-02-06,231.29,233.80,230.43,233.22,232.17,29925300.0,NaN,NaN,NaN,232.47,...,NaN,228.53,2.76,0.012077,232.67,1.13,0.004857,228.27,2.16,0.009462
2025-02-07,232.60,234.00,227.26,227.63,226.61,39707200.0,230.826,NaN,NaN,233.22,...,NaN,231.29,1.31,0.005664,233.80,0.20,0.000855,230.43,-3.17,-0.013757

In [40]:
apple.to_csv('AAPL.csv')

In [41]:
chase.to_csv('JPM.csv')

In [42]:
microsoft.to_csv('MSFT.csv')

In [43]:
tesla.to_csv('TSLA.csv')